[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/arrivals"
  to = "/.netlify/functions/arrivals"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-store"
